# theme.py

BACKGROUND = "#0B3A32"
SIDEBAR_BG = "#062F2A"
TEXT_PRIMARY = "#9FFFCB"
TEXT_SECONDARY = "#6EE7A8"
APP_BG = SIDEBAR_BG
MODE_COLORS = {
    "ENERGY_SAVER": "#FF6B6B",
    "BALANCED": "#6EE7A8",
    "PERFORMANCE": "#4D96FF"
}
BUTTON_HOVER = "#1f3d3a"   # slightly brighter than BUTTON_BG
BUTTON_BG = "#124E45"
BUTTON_ACTIVE = "#1B7F6A"
